#!/usr/bin/env bash
# Modern Pterodactyl Auto-Installer (Debian 13)
# Features:
# - Interaktive Dialog-Menüs (dialog)
# - Farbige Status- & Fehlerausgaben
# - Eingabevalidierung (Domain, Email, Passwörter)
# - Externes Logfile (/var/log/pteroinstall.log)
# - Modularer Aufbau (Panel, Wings, All-in-one)
# - Auto-Update (Vergleich mit GitHub raw URL)
# - Flags supported: --panel, --wings, --all, --yes, --no-update
#
# Tested intent: Debian 13 (Bookworm). Do not run on other OSes.
#
# Author: generated by ChatGPT for your request
# ------------------------------------------------------------------------------

set -o pipefail

### CONFIG
LOGFILE="/var/log/pteroinstall.log"
GITHUB_RAW_URL="https://raw.githubusercontent.com/MrFirewall/Pterodactyl-Auto-Installer/9a27d90d326206d6b532874a7cb47c74a7918d15/install_pterodactyl.sh"
SELF_NAME="$(basename "$0")"
TMP_SELF="/tmp/${SELF_NAME}.new"
INSTALL_START_TS="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# Colors
CYAN="\e[36m"; GREEN="\e[32m"; RED="\e[31m"; YELLOW="\e[33m"; BOLD="\e[1m"; RESET="\e[0m"
OK="${GREEN}[✔]${RESET}"; ERR="${RED}[✘]${RESET}"; INFO="${CYAN}[➜]${RESET}"; WARN="${YELLOW}[!]${RESET}"

# Defaults
AUTO_YES=false      # if true, skip interactive prompts
NO_SELF_UPDATE=false
DEBIAN_CODENAME="$(lsb_release -cs 2>/dev/null || echo bookworm)"

# Parsed settings (filled interactively)
INSTALL_PANEL=false
INSTALL_WINGS=false

PANEL_DOMAIN=""
DB_PASSWORD=""
ADMIN_EMAIL=""
ADMIN_USERNAME=""
ADMIN_FIRST=""
ADMIN_LAST=""
ADMIN_PASS=""
APP_TIMEZONE="Europe/Berlin"

# Ensure logfile exists
mkdir -p "$(dirname "$LOGFILE")"
touch "$LOGFILE"
chmod 600 "$LOGFILE"

# Logging helper
log() {
  local level="$1"; shift
  local msg="$*"
  echo -e "$(date -Iseconds) [$level] $msg" >>"$LOGFILE"
}
# Console helper
cecho() { echo -e "$*"; }
info()  { cecho "${INFO} $*" ; log "INFO" "$*"; }
ok()    { cecho "${OK} $*" ; log "OK" "$*"; }
warn()  { cecho "${WARN} $*" ; log "WARN" "$*"; }
error() { cecho "${ERR} $*" ; log "ERROR" "$*"; }

# Trap to log unexpected exit
on_exit() {
  local rc=$?
  if [ $rc -ne 0 ]; then
    error "Installer beendet mit Fehlercode $rc. Prüfe $LOGFILE für Details."
  else
    ok "Installer beendet (Exit code 0)."
  fi
}
trap on_exit EXIT

### BASIC CHECKS
if [ "$(id -u)" -ne 0 ]; then
  error "Dieses Skript muss als root ausgeführt werden."
  exit 1
fi

# parse args
while [ $# -gt 0 ]; do
  case "$1" in
    --panel) INSTALL_PANEL=true; shift ;;
    --wings) INSTALL_WINGS=true; shift ;;
    --all) INSTALL_PANEL=true; INSTALL_WINGS=true; shift ;;
    --yes|-y) AUTO_YES=true; shift ;;
    --no-update) NO_SELF_UPDATE=true; shift ;;
    --help|-h) echo "Usage: $0 [--panel] [--wings] [--all] [--yes] [--no-update]"; exit 0;;
    *) shift ;;
  esac
done

### UTILS
# Check and install dialog if missing
ensure_dialog() {
  if ! command -v dialog >/dev/null 2>&1; then
    info "Dialog nicht gefunden — installiere dialog..."
    apt-get update -y >>"$LOGFILE" 2>&1
    apt-get install -y dialog >>"$LOGFILE" 2>&1 || { error "Konnte dialog nicht installieren."; exit 1; }
  fi
}

# Validate domain (simple)
valid_domain() {
  local d="$1"
  # Allow wildcard? No. Basic domain validation (letters, digits, dash, dot)
  if [[ "$d" =~ ^([a-zA-Z0-9][-a-zA-Z0-9]{0,62}\.)+[a-zA-Z]{2,}$ ]]; then
    return 0
  fi
  return 1
}

# Validate email (simple)
valid_email() {
  local e="$1"
  if [[ "$e" =~ ^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$ ]]; then
    return 0
  fi
  return 1
}

# Validate password (min 8, contains upper/lower/digit)
valid_password() {
  local p="$1"
  if [ "${#p}" -lt 8 ]; then
    return 1
  fi
  if ! [[ "$p" =~ [A-Z] ]] || ! [[ "$p" =~ [a-z] ]] || ! [[ "$p" =~ [0-9] ]]; then
    return 1
  fi
  return 0
}

# Simple spinner for long tasks
spinner_start() {
  local msg="$1"; printf "%s " "$msg"
  ( while true; do for s in '/-\|'; do printf "\b%s" "$s"; sleep 0.12; done; done ) &
  SPINNER_PID=$!
  disown
}
spinner_stop() {
  if [ -n "$SPINNER_PID" ] && kill -0 "$SPINNER_PID" 2>/dev/null; then
    kill "$SPINNER_PID" >/dev/null 2>&1 || true
    wait "$SPINNER_PID" 2>/dev/null || true
    printf "\b ✓\n"
    unset SPINNER_PID
  fi
}

# Self update routine: download from GITHUB_RAW_URL and compare sha256
self_update_prompt() {
  [ "$NO_SELF_UPDATE" = true ] && return
  if $AUTO_YES; then
    info "Auto-Update übersprungen wegen --yes (keine Interaktion)."
    return
  fi
  info "Prüfe auf neue Installer-Version..."
  if ! curl -fsSL -o "$TMP_SELF" "$GITHUB_RAW_URL"; then
    warn "Konnte neue Version nicht herunterladen — überspringe Update."
    rm -f "$TMP_SELF" 2>/dev/null || true
    return
  fi
  chmod +x "$TMP_SELF"
  local oldsum newsum
  oldsum="$(sha256sum "$0" | awk '{print $1}')"
  newsum="$(sha256sum "$TMP_SELF" | awk '{print $1}')"
  if [ "$oldsum" != "$newsum" ]; then
    dialog --title "Installer Update verfügbar" --yesno "Eine neuere Version des Installers wurde gefunden. Möchten Sie auf die neue Version aktualisieren und das Skript neu starten?" 10 60
    if [ $? -eq 0 ]; then
      info "Aktualisiere Installer und starte neu..."
      mv "$TMP_SELF" "$0" || { error "Update fehlgeschlagen (mv)."; rm -f "$TMP_SELF"; return; }
      chmod +x "$0"
      exec "$0" "$@" # restart with original args
      exit 0
    else
      warn "Benutzer hat Update abgelehnt. Führe aktuellen Installer weiter aus."
      rm -f "$TMP_SELF"
    fi
  else
    info "Keine neuere Installer-Version gefunden."
    rm -f "$TMP_SELF"
  fi
}

# Run command but log stdout/stderr; on error print colored message and optional exit
run_logged() {
  local cmd="$*"
  log "CMD" "$cmd"
  eval "$cmd" >>"$LOGFILE" 2>&1
  local rc=$?
  if [ $rc -ne 0 ]; then
    error "Befehl fehlgeschlagen: $cmd (rc=$rc). Siehe $LOGFILE"
    return $rc
  fi
  return 0
}

### INTERACTIVE UI (dialog)
ensure_dialog

# If no explicit selection from flags, show dialog
if ! $INSTALL_PANEL && ! $INSTALL_WINGS; then
  CHOICE=$(dialog --clear --stdout --title "Pterodactyl Installation" \
    --menu "Was möchten Sie installieren?" 15 60 4 \
    1 "Pterodactyl Panel (Web, DB, Redis)" \
    2 "Pterodactyl Wings (Docker Host)" \
    3 "Beides (All-in-One)" \
    4 "Abbrechen")
  case "$CHOICE" in
    1) INSTALL_PANEL=true ;;
    2) INSTALL_WINGS=true ;;
    3) INSTALL_PANEL=true; INSTALL_WINGS=true ;;
    *) clear; exit 0 ;;
  esac
fi

# Auto-update prompt (only before heavy work)
self_update_prompt

# If panel is selected, ask for required details via mixedform
if $INSTALL_PANEL; then
  FORM_RESULT=$(dialog --stdout --title "Panel Setup" --form "Geben Sie die Panel-Einstellungen ein" 18 70 12 \
    "Panel Domain (FQDN):" 1 1 "$PANEL_DOMAIN" 1 28 40 0 \
    "DB Passwort:"           3 1 "" 3 28 40 0 \
    "Admin E-Mail:"          5 1 "$ADMIN_EMAIL" 5 28 40 0 \
    "Admin Benutzername:"    7 1 "$ADMIN_USERNAME" 7 28 40 0 \
    "Admin Vorname:"         9 1 "$ADMIN_FIRST" 9 28 40 0 \
    "Admin Nachname:"       11 1 "$ADMIN_LAST" 11 28 40 0 \
    "Admin Passwort:"       13 1 "" 13 28 40 0 \
    "Timezone (Europe/Berlin):" 15 1 "$APP_TIMEZONE" 15 28 40 0 )
  # read results
  IFS=$'\n' read -r PANEL_DOMAIN DB_PASSWORD ADMIN_EMAIL ADMIN_USERNAME ADMIN_FIRST ADMIN_LAST ADMIN_PASS APP_TIMEZONE <<<"$FORM_RESULT"

  # validations
  if ! valid_domain "$PANEL_DOMAIN"; then
    dialog --msgbox "Ungültiger FQDN: $PANEL_DOMAIN\nBitte erneut starten und eine gültige Domain angeben." 8 60
    error "Ungültiger Domain-Eintrag: $PANEL_DOMAIN"
    clear; exit 1
  fi
  if ! valid_email "$ADMIN_EMAIL"; then
    dialog --msgbox "Ungültige E-Mail: $ADMIN_EMAIL\nBitte erneut starten und eine gültige E-Mail angeben." 8 60
    error "Ungültige Admin E-Mail: $ADMIN_EMAIL"
    clear; exit 1
  fi
  if ! valid_password "$ADMIN_PASS"; then
    dialog --msgbox "Admin Passwort muss mindestens 8 Zeichen lang sein und Groß-/Kleinbuchstaben sowie Zahlen enthalten." 10 60
    error "Schwaches Admin Passwort angegeben."
    clear; exit 1
  fi
  # DB password fallback
  if [ -z "$DB_PASSWORD" ]; then
    # create random 16 char password
    DB_PASSWORD="$(head -c 32 /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 16)"
    warn "Kein DB-Passwort angegeben, generiere sicheres Passwort."
  fi
fi

### INSTALLATION MODULES
install_common_dependencies() {
  info "System aktualisieren und Basis-Pakete installieren..."
  spinner_start "apt update && apt upgrade"
  run_logged "apt-get update -y"
  run_logged "DEBIAN_FRONTEND=noninteractive apt-get upgrade -y"
  spinner_stop

  spinner_start "Installiere Basis-Tools"
  run_logged "apt-get install -y curl wget gnupg2 ca-certificates lsb-release apt-transport-https software-properties-common unzip tar git pwgen"
  spinner_stop
}

install_php_and_redis_repo() {
  info "Füge PHP 8.3 (sury) und Redis Repositories hinzu..."
  # Sury PHP
  if ! grep -q "packages.sury.org" /etc/apt/sources.list.d/* 2>/dev/null; then
    run_logged "apt-get install -y apt-transport-https lsb-release ca-certificates curl"
    run_logged "curl -fsSL https://packages.sury.org/php/README.txt | bash" || warn "Sury Install-Skript konnte fehlschlagen (prüfen)"
    # Also add explicit entry just in case
    echo "deb https://packages.sury.org/php/ ${DEBIAN_CODENAME} main" > /etc/apt/sources.list.d/sury-php.list
  fi
  # Redis
  if ! grep -q "packages.redis.io" /etc/apt/sources.list.d/* 2>/dev/null; then
    run_logged "curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg" || warn "Redis key import failed"
    echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb ${DEBIAN_CODENAME} main" > /etc/apt/sources.list.d/redis.list
  fi
  run_logged "apt-get update -y"
}

install_panel_dependencies() {
  info "Installiere Panel-Abhängigkeiten (PHP 8.3, MariaDB, Nginx, Redis)..."
  spinner_start "Installiere PHP + MariaDB + Nginx + Redis"
  run_logged "DEBIAN_FRONTEND=noninteractive apt-get install -y php8.3 php8.3-fpm php8.3-cli php8.3-mbstring php8.3-xml php8.3-mysql php8.3-zip php8.3-curl php8.3-bcmath php8.3-gd php8.3-intl mariadb-server nginx redis-server"
  spinner_stop

  info "Installiere Composer..."
  if ! command -v composer >/dev/null 2>&1; then
    run_logged "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
  fi
}

install_mariadb_setup() {
  info "Konfiguriere MariaDB (Datenbank und Benutzer für Panel)..."
  # secure installation minimal automated: ensure root unix_socket auth is working (default on Debian)
  # Create database & user
  cat > /tmp/panel_db_setup.sql <<EOF
CREATE DATABASE IF NOT EXISTS panel;
CREATE USER IF NOT EXISTS 'pterodactyl'@'127.0.0.1' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON panel.* TO 'pterodactyl'@'127.0.0.1';
FLUSH PRIVILEGES;
EOF
  run_logged "mysql < /tmp/panel_db_setup.sql" || { error "MariaDB-Befehle fehlgeschlagen."; return 1; }
  rm -f /tmp/panel_db_setup.sql
  ok "MariaDB: Datenbank 'panel' und Benutzer 'pterodactyl' erstellt."
}

install_panel_files() {
  info "Hole Pterodactyl Panel Release, installiere und konfiguriere..."
  mkdir -p /var/www/pterodactyl
  cd /var/www/pterodactyl || return 1

  spinner_start "Download Panel"
  run_logged "curl -Lo panel.tar.gz https://github.com/pterodactyl/panel/releases/latest/download/panel.tar.gz"
  run_logged "tar -xzf panel.tar.gz --strip-components=0 -C /var/www/pterodactyl"
  run_logged "rm -f panel.tar.gz"
  spinner_stop

  run_logged "cp .env.example .env"
  run_logged "chown -R www-data:www-data /var/www/pterodactyl"
  run_logged "chmod -R 755 storage bootstrap/cache || true"

  info "Installiere PHP Abhängigkeiten via Composer (kann einige Minuten dauern)..."
  spinner_start "composer install"
  run_logged "cd /var/www/pterodactyl && COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader"
  spinner_stop

  info "Erzeuge APP-Key und konfiguriere Umgebungsvariablen..."
  run_logged "cd /var/www/pterodactyl && php artisan key:generate --force"
  run_logged "cd /var/www/pterodactyl && php artisan p:environment:database --host=127.0.0.1 --port=3306 --database=panel --username=pterodactyl --password='${DB_PASSWORD}' || true"
  run_logged "cd /var/www/pterodactyl && php artisan p:environment:mail --driver=mail || true"
  run_logged "cd /var/www/pterodactyl && php artisan p:environment:setup --url=\"https://${PANEL_DOMAIN}\" --timezone=\"${APP_TIMEZONE}\" --cache=redis --session=redis --queue=redis || true"

  info "Migriere Datenbank und seed initiale Daten..."
  spinner_start "artisan migrate & seed"
  run_logged "cd /var/www/pterodactyl && php artisan migrate --seed --force"
  spinner_stop

  info "Lege ersten Admin-Benutzer an..."
  run_logged "cd /var/www/pterodactyl && php artisan p:user:make --email='${ADMIN_EMAIL}' --username='${ADMIN_USERNAME}' --name-first='${ADMIN_FIRST}' --name-last='${ADMIN_LAST}' --password='${ADMIN_PASS}' --admin=1 || true"

  run_logged "chown -R www-data:www-data /var/www/pterodactyl"
  ok "Panel-Dateien installiert und (teilweise) konfiguriert."
}

install_nginx_site() {
  info "Erstelle Nginx Site-Konfiguration für ${PANEL_DOMAIN}..."
  cat > /etc/nginx/sites-available/pterodactyl.conf <<'NGINX_CONF'
server {
    listen 80;
    server_name __PANEL_DOMAIN__;
    root /var/www/pterodactyl/public;
    index index.php;

    access_log /var/log/nginx/pterodactyl.app-access.log;
    error_log  /var/log/nginx/pterodactyl.app-error.log error;

    client_max_body_size 100m;
    client_body_timeout 120s;
    sendfile off;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_PROXY "";
        fastcgi_intercept_errors off;
        include /etc/nginx/fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
NGINX_CONF

  sed -i "s|__PANEL_DOMAIN__|${PANEL_DOMAIN}|g" /etc/nginx/sites-available/pterodactyl.conf
  rm -f /etc/nginx/sites-enabled/default
  ln -sf /etc/nginx/sites-available/pterodactyl.conf /etc/nginx/sites-enabled/pterodactyl.conf
  run_logged "systemctl restart nginx || true"
  ok "Nginx konfiguriert (HTTP). Für TLS: Let's Encrypt kann später hinzugefügt werden."
}

install_queue_worker() {
  info "Erstelle pteroq systemd Service für Queue Worker..."
  cat > /etc/systemd/system/pteroq.service <<'SERVICE'
[Unit]
Description=Pterodactyl Queue Worker
After=redis-server.service

[Service]
User=www-data
Group=www-data
Restart=always
ExecStart=/usr/bin/php /var/www/pterodactyl/artisan queue:work --queue=high,standard,low --sleep=3 --tries=3
StartLimitInterval=180
StartLimitBurst=30
RestartSec=5s

[Install]
WantedBy=multi-user.target
SERVICE

  run_logged "systemctl enable --now pteroq.service"
  ok "pteroq.service aktiviert."
}

# Wings installation
install_docker() {
  info "Installiere Docker CE..."
  spinner_start "Installiere Docker (get.docker.com)"
  run_logged "curl -fsSL https://get.docker.com | CHANNEL=stable bash"
  run_logged "systemctl enable --now docker"
  spinner_stop
  ok "Docker installiert."
}

install_wings_binary() {
  info "Lade Wings und bereite Systemd-Service vor..."
  mkdir -p /etc/pterodactyl
  local arch
  arch="$(uname -m)"
  if [ "$arch" = "x86_64" ] || [ "$arch" = "amd64" ]; then arch="amd64"; else arch="arm64"; fi
  local wings_url="https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_${arch}"
  run_logged "curl -Lo /usr/local/bin/wings ${wings_url}"
  run_logged "chmod +x /usr/local/bin/wings"
  cat > /etc/systemd/system/wings.service <<'WINGS_SERVICE'
[Unit]
Description=Pterodactyl Wings Daemon
After=docker.service
Requires=docker.service

[Service]
User=root
WorkingDirectory=/etc/pterodactyl
LimitNOFILE=4096
PIDFile=/var/run/wings/daemon.pid
ExecStart=/usr/local/bin/wings
Restart=on-failure
StartLimitInterval=180
StartLimitBurst=30
RestartSec=5s

[Install]
WantedBy=multi-user.target
WINGS_SERVICE

  ok "Wings binary & systemd service erstellt (nicht gestartet)."
  warn "Wings wird NICHT automatisch gestartet — Sie müssen die /etc/pterodactyl/config.yml aus dem Panel einfügen und anschließend 'systemctl enable --now wings' ausführen."
}

# Firewall notes
suggest_firewall() {
  warn "Stellen Sie sicher, dass die folgenden Ports erreichbar sind (je nach Setup):"
  echo " - 80/443 TCP (Panel)"
  echo " - 8080 TCP (Wings <-> Panel)"
  echo " - 2022 TCP (SFTP für Wings)"
  echo ""
  log "Firewall Hinweis: Ports 80/443/8080/2022 prüfen"
}

### MAIN RUN
info "Installation gestartet: ${INSTALL_START_TS}"
install_common_dependencies
install_php_and_redis_repo

if $INSTALL_PANEL; then
  install_panel_dependencies
  install_mariadb_setup
  install_panel_files
  install_nginx_site
  install_queue_worker
fi

if $INSTALL_WINGS; then
  install_docker
  install_wings_binary
fi

# Final messages
clear
echo -e "${GREEN}======================================================${RESET}"
echo -e "${GREEN}✅ Installation abgeschlossen${RESET}"
echo -e "${GREEN}======================================================${RESET}"
if $INSTALL_PANEL; then
  echo -e "${BOLD}Panel:${RESET} https://${PANEL_DOMAIN}"
  echo -e "Admin Benutzer: ${ADMIN_USERNAME}   E-Mail: ${ADMIN_EMAIL}"
fi
if $INSTALL_WINGS; then
  echo -e "${BOLD}Wings:${RESET} /etc/pterodactyl (Konfigurationsdatei fehlt noch)"
  echo -e "Um Wings zu aktivieren:"
  echo -e " - Erstellen Sie im Panel einen Node und kopieren Sie die Konfiguration (Konfigurations-Tab)."
  echo -e " - Legen Sie diese in /etc/pterodactyl/config.yml ab und führen Sie:"
  echo -e "     systemctl enable --now wings"
fi

suggest_firewall
echo ""
echo -e "Logs: ${LOGFILE}"
ok "Fertig."

# Keep exit 0
exit 0
